NUMBERS_POS = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
NUMBERS_ZERO = ["0"]
NUMBERS = NUMBERS_POS + NUMBERS_ZERO

OPERATORS_COMMUTATIVE = ["+", "-", "*"]
OPERATORS_DIV = ["/"]
OPERATORS = OPERATORS_COMMUTATIVE + OPERATORS_DIV

RELATIONS = ["="]

LENGTH = 8
EXPRS_FILENAME = "expressions.txt"
DONE_STR = "done"
